# © 2024 Carl Åstholm
# SPDX-License-Identifier: MIT

# REUSE <https://reuse.software/>
version = 1

[[annotations]]
path = [
    "SDL-breakout/preview.gif"
]
SPDX-FileCopyrightText = "2024 Carl Åstholm"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "SDL-breakout/sounds.wav",
    "SDL-breakout/sprites.bmp"
]
SPDX-FileCopyrightText = "Kenney <www.kenney.nl>"
SPDX-License-Identifier = "CC0-1.0"
