# © 2024 Carl Åstholm
# SPDX-License-Identifier: MIT

# REUSE <https://reuse.software/>
version = 1

[[annotations]]
path = "breakout/preview.gif"
SPDX-FileCopyrightText = "2024 Carl Åstholm"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "breakout/sounds.wav",
    "breakout/sprites.bmp"
]
SPDX-FileCopyrightText = "NONE" # Kenney <www.kenney.nl>
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "snake/preview.gif",
    "opengl-sdl/preview.png",
    "opengl-glfw/preview.png"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
